#!/bin/sh

# This is a rather sucky way of doing this, but oh well.
# I hate build systems.
FILES="errorReport.cmo syntree.cmo parse.cmo lex.cmo symtable.cmo main.cmo"

OPTFILES="errorReport.cmx syntree.cmx symtbl.cmx parse.cmx lex.cmx \
       modules.cmx ir.cmx irTransform.cmx fpConverter.cmx codegenHelp.cmx \
       codegen.cmx semant.cmx x86nasm.cmx main.cmx"

LIBS="str.cma"
OPTLIBS="str.cmxa"

OCAMLLINK=ocamlc.opt
OCAMLOPTLINK=ocamlopt.opt
TARGET=clc

$OCAMLLINK -g -o $TARGET $LIBS $FILES
#$OCAMLOPTLINK -o $TARGET $OPTLIBS $OPTFILES
